name: build-test

on:
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
    - ready_for_review
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - run: |
        # set default git config for unit tests
        git config --global user.email "gha@ci"
        git config --global user.name "ci"
    - run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - uses: ./
      with:
        config_file: .github/rules.yml
    - name: Only run if a diff has been detected
      if: env.DIFF_DETECTED
      run: echo diff detected
