name: build-test

on:
  pull_request:
  push:
    branches:
    - master
    - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        # set default git config for unit tests
        git config --global user.email "gha@ci"
        git config --global user.name "ci"
    - run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: echo env var previously set
      if: always()
      run: |
        echo "::echo::on"
        echo '$DIFF_DETECTED=${{ env.DIFF_DETECTED }}'
    - name: Run if diff detected
      if: env.DIFF_DETECTED
      run: |
        echo diff detected
